config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#                dashboard GET    /dashboard(.:format)                             dashboard#index
#         new_user_session GET    /users/sign_in(.:format)                         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                        devise/sessions#destroy
#            user_password POST   /users/password(.:format)                        devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                   devise/passwords#edit
#                          PATCH  /users/password(.:format)                        devise/passwords#update
#                          PUT    /users/password(.:format)                        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                          devise/registrations#cancel
#        user_registration POST   /users(.:format)                                 devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                            devise/registrations#edit
#                          PATCH  /users(.:format)                                 devise/registrations#update
#                          PUT    /users(.:format)                                 devise/registrations#update
#                          DELETE /users(.:format)                                 devise/registrations#destroy
#                     root GET    /                                                dashboard#index
#     unauthenticated_root GET    /                                                home#index
#     profile_appointments POST   /profiles/:profile_id/appointments(.:format)     appointments#create
#  new_profile_appointment GET    /profiles/:profile_id/appointments/new(.:format) appointments#new
#      profile_appointment PATCH  /profiles/:profile_id/appointments/:id(.:format) appointments#update
#                          PUT    /profiles/:profile_id/appointments/:id(.:format) appointments#update
#             edit_profile GET    /profiles/:id/edit(.:format)                     profiles#edit
#                  profile GET    /profiles/:id(.:format)                          profiles#show
#                          PATCH  /profiles/:id(.:format)                          profiles#update
#                          PUT    /profiles/:id(.:format)                          profiles#update
#

Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'settings' => 'dashboard#settings'
  get 'book-class' => 'dashboard#book_class'
  post 'book-class' => 'dashboard#book_class_search'
  get 'class-history' => 'dashboard#class_history'

  devise_for :users

  authenticated :user do
    root 'dashboard#index', as: :root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

  resources :profiles, only: [:show, :update, :edit] do
    resources :educations , only: [ :update, :edit, :create]
    resources :experiences , only: [ :update, :edit, :create]
    # creating the appointments for the user.
    resources :appointments, only: [:new, :update, :create] do
      resources :payments, only: [:new, :create] do
        member do
          get 'make'
          post 'confirm'
        end
      end
      member do
        put 'accept_class'
        put 'cancel_class'
        put 'start_class'
      end
    end

    resources :cards, only: [:new, :create, :destroy]

    get 'payments/pending' => 'payments#pending', as: :pending_payments
    post 'payments#withdraw' => 'payments#withdraw', as: :withdraw_payments
  end

  resources :appointments, only: [] do
    resources :testimonials, only: [:create]
  end

  get 'messages' => 'messages#index', as: :messages
  get 'messages/:id/new' => 'messages#new', as: :new_message
  post 'messages/:id' => 'messages#create', as: :create_message
  post 'messages/:id/reply' => 'messages#reply', as: :reply_message
  get 'messages/:id/conversation' => 'messages#get_messages_list'

  get 'aboutus' => 'home#aboutus'
  get 'faq' => 'home#faq'
  get 'course' => 'home#course'
  get 'whywikilesson' => 'home#whywikilesson'
  get 'blog' => 'home#blog'
  get 'contactus' => 'home#contactus'
  get 'howitwork' => 'home#howitwork'

  # get the user class info.
  get 'classinfo/:id' => 'appointments#class_info'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!, except: [:book_class_search, :book_class]
  def index
    @user = current_user
    if @user.has_role? :student

      @awating_confirmation = @user.student_appointments.where(completed: 0, accepted: false)

      @awating_payment = @user.student_appointments.where(completed: 0, accepted: true, class_valid: false)
      @registered_class = @user.student_appointments.where(completed: 0, accepted: true, class_valid: true)
    else
      @awating_confirmation = @user.teacher_appointments.where(completed: 0, accepted: false)

      @awating_payment = @user.teacher_appointments.where(completed: 0, accepted: true, class_valid: false)
      @registered_class = @user.teacher_appointments.where(completed: 0, accepted: true, class_valid: true)

    end
  end

  def settings
  end

  def book_class
    if current_user != nil and current_user.profile.profile_status != 100
      redirect_to edit_profile_path(current_user.profile), notice: 'You need to complete your profile first.'
    end
    @teachers = []
    @relevant = false
    params[:teacher] = {}
    params[:teacher][:gender] = 'no-filter-gender'
    params[:teacher][:rating] = 'no-filter-rating'
    params[:teacher][:availability] = 'online'
  end

  def book_class_search
    gender = params[:teacher][:gender]
    rating = params[:teacher][:rating]
    availability = Profile::AVAILABILITY_GET[params[:teacher][:availability]]
    availability = Profile::AVAILABILITY_GET['online'] unless availability
    standard = params[:teacher][:standard]
    @teachers = Profile.where(availability: availability).tagged_with(params[:teacher][:subject], profile_status: 100)
    if standard
      @teachers.where(standard: standard)
    end
    if rating == '4+'
      @teachers = @teachers.where('average_rating >= 4.0')
    end
    if gender == 'male' || gender == 'female'
      @teachers = @teachers.where(gender: Profile::GENDER_GET[gender])
    end
    @relevant = true
    render 'book_class'
  end

  def class_history
    if current_user.has_role? :teacher
      @classes = Appointment.where(teacher_id: current_user.id, class_status: 3)
    else
      @classes = Appointment.where(student_id: current_user.id, class_status: 3)
    end
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_awating_confirmation.html.erb
<% if @awating_confirmation.present? %>

    <div class="awaiting-section">
      <h3>Awaiting Confirmation</h3>
      <% @awating_confirmation.each do |f| %>
          <div class="panel panel-warning pending-section-wrapper">
            <div class="panel-heading header">
              <h4 class="panel-title">Awaiting Confirmation</h4>
            </div>
            <div class="panel-body pending-class-div">
              <div class="mediaobject-img-div">
                <%= image_tag '11-01.png', class: 'teacher-img' %>
              </div>
              <div class="pending-class-info">
                <table>
                  <tr>
                    <td>
                    <th>Name:</th>
                    </td>
                    <td>
                      <% if current_user.has_role? :student %>
                          <%= f.teacher.profile.fullname %>
                      <% else %>
                          <%= f.student.profile.fullname %>
                      <% end %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Class Date:</th>
                    </td>
                    <td>
                      <%= f.appointment_date.strftime('%B %d, %Y') %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>No. of hours:</th>
                    </td>
                    <td>
                      <%= pluralize(f.class_hours, 'hour', 'hours') %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Topic:</th>
                    </td>
                    <td>
                      <%= f.topic %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Description:</th>
                    </td>
                    <td>
                      <%= f.description %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th></th>
                    </td>
                    <td>
                      <%= link_to 'Cancel ', cancel_class_profile_appointment_path(id: f.id, profile_id: @user.id), method: :put %>

                    </td>
                    <% if current_user.has_role? :teacher %>
                        <td>
                          <%= link_to 'Accept', accept_class_profile_appointment_path(id: f.id, profile_id: @user.id), method: :put %>
                        </td>
                    <% end %>

                  </tr>
                </table>
              </div>
            </div>
          </div> <!-- first end-->
      <% end %>
    </div>

<% end %>

app/views/dashboard/_awating_payment.html.erb
<% if @awating_payment.present? %>
    <div class="awaiting-section">
      <h3>Awaiting Payment</h3>
      <% @awating_payment.each do |f| %>
          <div class="panel panel-danger pending-section-wrapper">
            <div class="panel-heading header">
              <h4 class="panel-title">Awaiting Payment</h4>
            </div>
            <div class="panel-body pending-class-div">

              <div class="mediaobject-img-div">
                <%= image_tag '11-01.png', class: 'teacher-img' %>
              </div>
              <div class="pending-class-info">
                <table>
                  <tr>
                    <td>
                    <th>Name:</th>
                    </td>
                    <td>
                      <% if current_user.has_role? :student %>
                          <%= f.teacher.profile.fullname %>
                      <% else %>
                          <%= f.student.profile.fullname %>

                      <% end %>


                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Class Date:</th>
                    </td>
                    <td>
                      <%= f.appointment_date.strftime('%B %d, %Y') %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>No. of hours:</th>
                    </td>
                    <td>
                      <%= pluralize(f.class_hours, 'hour', 'hours') %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Topic:</th>
                    </td>
                    <td>
                      <%= f.topic %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Description:</th>
                    </td>
                    <td>
                      <%= f.description %>

                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th></th>
                    </td>
                    <td>
                      <% if current_user.has_role? :student %>
                          <%= link_to 'Make Payment', make_profile_appointment_payment_path(appointment_id: f.id, profile_id: @user.id, id: f.payment.id) %> |
                      <% end %>
                      <%= link_to 'Cancel ', cancel_class_profile_appointment_path(id: f.id, profile_id: @user.id), method: :put %>
                    </td>
                  </tr>
                </table>
              </div>

            </div>
          </div><!--first--end-->


      <% end %>
    </div>
<% end %>

app/views/dashboard/_registered_class.html.erb
<% if @registered_class.present?  %>
    <div class="awaiting-section">
      <h3>Registered Classes</h3>
      <% @registered_class.each do |f| %>
          <div class="panel panel-success pending-section-wrapper">
            <div class="panel-heading header">
              <h4 class="panel-title">Registered Classes</h4>
            </div>
            <div class="panel-body pending-class-div">

              <div class="mediaobject-img-div">
                <%= image_tag '11-01.png', class: 'teacher-img' %>
              </div>
              <div class="pending-class-info">
                <table>
                  <tr>
                    <td>
                    <th>Name:</th>
                    </td>
                    <td>
                      <% if current_user.has_role? :student %>
                          <%= f.teacher.profile.fullname %>
                      <% else %>
                          <%= f.student.profile.fullname %>

                      <% end %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Class  Date:</th>
                    </td>
                    <td>
                      <%= f.appointment_date.strftime('%B %d, %Y') %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>No. of hours:</th>
                    </td>
                    <td>
                      <%= pluralize(f.class_hours, 'hour', 'hours') %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Topic:</th>
                    </td>
                    <td>
                      <%= f.topic %>
                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th>Description:</th>
                    </td>
                    <td>

                    </td>
                  </tr>
                  <tr>
                    <td>
                    <th></th>
                    </td>
                    <td>
                      <%= link_to 'Cancel ', cancel_class_profile_appointment_path(id: f.id, profile_id: @user.profile.id), method: :put %>
                    </td>
                  </tr>
                  <tr>
                    <td><th></th></td>
                    <td>
                      <% if f.class_status == 1 %>
                          <% if f["started_by_#{current_role}"] %>
                              You started the class
                          <% else %>
                              <%= link_to 'Start Class', start_class_profile_appointment_path(id: f.id, profile_id: @user.profile.id), method: :put %>
                          <% end %>
                          <%= "(#{opposite_role.titleize} has #{f["started_by_#{opposite_role}"] ? '' : 'not'} started)" %>
                      <% elsif f.class_status == 2 %>
                          In Progress
                      <% end %>
                    </td>
                  </tr>
                </table>
              </div>

            </div>

          </div><!--first--end-->
      <% end %>

    </div>
<% end %>

app/views/dashboard/book_class.html.erb
<section class="my-teacher-hero-section">
  <div class="texture-div">
    <h1>view <span class="font-blue">teachers for</span></h1>
    <div style="display:flex; justify-content:center;">
      <div class="buttons-div">
        <%= form_for 'teacher', html: {style: 'display: flex', id: 'book-class-form'} do |f| %>
            <select name="teacher[standard]" id="">
              <option value="" class="disable hidden">choose grade</option>
              <% Profile::STANDARD.each do |standard| %>
                  <option value="<%= standard[0] %>" <% if params[:teacher] and params[:teacher][:standard].to_i == standard[0].to_i %>selected="selected"<% end %>><%= standard[1] %></option>
              <% end %>
            </select>
            <div class="btn-container">
              <i class="fa fa-search fa-2x"></i>
              <input type="search" placeholder="search" name="teacher[subject]" value="<%= params[:teacher] ? params[:teacher][:subject] : '' %>">
            </div>
            <%= f.hidden_field 'gender', value: (params[:teacher] ? params[:teacher][:gender] : 'no-filter-gender') %>
            <%= f.hidden_field 'rating', value: (params[:teacher] ? params[:teacher][:rating] : 'no-filter-rating') %>
            <%= f.hidden_field 'availability', value: params[:teacher][:availability] %>
            <button class="btn" type="submit">Search</button>
        <% end %>
      </div>
    </div>
    <section class="my-teacher-body">
      <div class="row">
        <div class="col-md-3">
          <div class="range-div">
            <h2>price range</h2>
            <input type="range" step="1" min="500" max="2500">
          </div>
          <form class="status-div">
            <i class="fa fa-wifi"></i>
            status
            <ul>
              <li>
                <input type="radio" id="online-option" name="selector" class="filter-event" value="online" <%= params[:teacher] and params[:teacher][:availability] == 'online' ? 'checked' : '' %>>
                <label for="online-option">online</label>
                <div class="check"><div class="inside"></div></div>
              </li>

              <li>
                <input type="radio" id="offline" name="selector" class="filter-event" value="offline" <%= params[:teacher] and params[:teacher][:availability] == 'offline' ? 'checked' : '' %>>
                <label for="offline">offline</label>
                <div class="check"></div>
              </li>
            </ul>
          </form>
          <form class="gender-div">
            <i class="fa fa-venus-mars" aria-hidden="true"></i>
            <span>gender</span>
            <ul>
              <li>
                <input type="radio" id="gender-no-filter" name="selector" class="filter-event" value="no-filter-gender" <%= params[:teacher] and params[:teacher][:gender] == 'no-filter-gender' ? 'checked' : '' %>>
                <label for="gender-no-filter">no filter</label>

                <div class="check"></div>
              </li>

              <li>
                <input type="radio" id="male-option" name="selector" class="filter-event" value="male" <%= params[:teacher] and params[:teacher][:gender] == 'male' ? 'checked' : '' %>>
                <label for="male-option">male</label>

                <div class="check"><div class="inside"></div></div>
              </li>

              <li>
                <input type="radio" id="female-option" name="selector" class="filter-event" value="female" <%= params[:teacher] and params[:teacher][:gender] == 'female' ? 'checked' : '' %>>
                <label for="female-option">female</label>

                <div class="check"><div class="inside"></div></div>
              </li>
            </ul>
          </form>
          <form class="rating-div">
            <img src="images/rating.png" alt="" width="35">
            <span>rating</span>
            <ul>
              <li>
                <input type="radio" id="rating-no-filter" name="selector" value="no-filter-rating" class="filter-event" <%= params[:teacher] and params[:teacher][:rating] == 'no-filter-rating' ? 'checked' : '' %>>
                <label for="rating-no-filter">no filter</label>
                <div class="check"></div>
              </li>

              <li>
                <input type="radio" id="rating-option" name="selector" value="4+" class="filter-event" <%= params[:teacher] and params[:teacher][:rating] == '4+' ? 'checked' : '' %>>
                <label for="rating-option">show only 4+</label>
                <div class="check"><div class="inside"></div></div>
              </li>
            </ul>
          </form>
        </div>
        <div class="col-md-9 teacher-profile-side" id="results-div" data-relevant="<%= @relevant %>">
          <% @teachers.each do |teacher| %>
              <div class="teacher-div">
                <div class="row">
                  <div class="col-md-3 col-sm-4 col-xs-10">
                    <%= image_tag teacher.avatar_url(:thumb), class: 'img-responsive' %>
                    <div class="status-div">
                      <span class="online-circle offline-circle"></span>
                      <span><%= Profile::AVAILABILITY[teacher.availability] %></span>
                    </div>
                  </div>
                  <div class="col-md-5">
                    <h3 class="name"><%= link_to teacher.fullname, profile_path(teacher) %></h3>
                    <h4>teaches <%= teacher.subjects.pluck(:name).join(', ').titleize %></h4>
                    <h4>teaching experience: <b>5 years</b></h4>
                    <a href="<%= profile_path(teacher.user) %>" class="view-profile-link">view profile and pricing plans</a>
                  </div>
                  <div class="col-md-4 trial-session-div">
                    <h4><span><b>4.9</b></span>
                      <span><%= number_to_currency(teacher.rate) %>/hr</span></h4>
                    <a href="online-lesson.html">Book Online</a>
                    <a href="inperson-lesson.html">In-Person lesson</a>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </section>
  </div>
</section>

app/views/dashboard/class_history.html.erb
<% @classes.each do |klass| %>
    <p>
      <%= klass.topic %>
      <% unless klass.testimonial_given?(current_user) %>
          , Give testimonial
          <%= form_for Testimonial.new, url: appointment_testimonials_path(klass) do |f| %>
              <%= f.text_area :description %> <br>
              <%= f.hidden_field :rating, id: "#{klass.id}_rating" %>
              <div class="rateYo" data-id="<%= klass.id %>"></div>
              <%= f.submit 'Rate' %>
          <% end %>
      <% end %>
    </p>
<% end %>

app/views/dashboard/index.html.erb
<div class="dashboard">
  <section class="student-profile-section class-overview">
    <% if current_user.has_role? :student %>
        <h1>classes overview (student)</h1>

    <% else %>
        <h1>classes overview (teacher)</h1>

    <% end %>

    <div class="student-profile-div ">
      <div class="personal-description-div">
        <div class="row">
          <div class="col-md-8 col-sm-12">
            <div class="personal-description-border teacher-overviw-padding upcoming-classes open">

            <%= render 'layouts/alerts' %>
              <% if current_user.profile.profile_status.present?  %>
                <% if current_user.profile.profile_status < 100 %>
                    <h2>Your current profile is: <%=  current_user.profile.profile_status %>% complete.</h2>
                    <h5 class="text-info">You cannot search nor be listed in the search if your profile is not completed. <%= link_to 'Click here', edit_profile_path(current_user.profile), style: 'color: #cc3333' %> to edit your profile.</h5>

                <% end %>
                <% end %>



              <!--<div class="filter-div">-->
              <!--<h4>Filter By:</h4>-->
              <!--<button class="">Awaiting classes</button>-->
              <!--<button class="">Pending classes</button>-->
              <!--<button class="">Registered classes</button>-->
              <%  if @awating_confirmation.present? or @awating_payment.present? or @registered_class.present?%>
                  <%= render 'dashboard/awating_confirmation' %>
                  <%= render 'dashboard/awating_payment' %>
                  <%= render 'dashboard/registered_class' %>
              <% else %>
                  <p>Sorry you have not book any class till now.</p>
              <% end %>

              <!---payment-section--->


              <!---registered -section--->

            </div>

          </div>
          <div class="col-md-4 col-sm-12 teacher-tips-col">


            <% if current_user.has_role? :teacher %>

                <div class="teacher-tip-div">
                  <h3>Earnings</h3>
                  <p>
                    Available Now :- <%= available_earnings %>
                  </p>
                  <h5 class="word_color"><a href="<%= profile_pending_payments_path(current_user.profile) %>">View pending earnings</a> ></h5>
                  <h5 class="word_color learn-payment"><a href="#">Learn about the payment schedule</a></h5>
                </div>

            <% end %>
            <div class="teacher-tip-div hidden-xs">
              <h3>Tips for success</h3>
              <p class="techer-tips-p">
                As you gain client and complex project, make sure to keep  your profile up to date? Are there any skill or experience you can add. Can you command a higher rate?
              </p>
              <div class="previous-next-section">
                <p>
                  4 Tips
                </p>
                <div class="">
                  <a href="#">Previous</a>
                  <a href="#">Next</a>
                </div>
              </div>
            </div>
            <!--<div class="img-graph-div">-->
            <!--<span class="img-graph">-->
            <!--</span>-->
            <!--<a href="#">Reports ></a>-->
            <!--</div>-->
          </div>
        </div>
      </div>
    </div>

  </section>
</div>

app/views/dashboard/settings.html.erb
<%= link_to 'Add Card', new_profile_card_path(profile_id: current_user.profile.id) %>