config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#                dashboard GET    /dashboard(.:format)                             dashboard#index
#         new_user_session GET    /users/sign_in(.:format)                         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                        devise/sessions#destroy
#            user_password POST   /users/password(.:format)                        devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                   devise/passwords#edit
#                          PATCH  /users/password(.:format)                        devise/passwords#update
#                          PUT    /users/password(.:format)                        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                          devise/registrations#cancel
#        user_registration POST   /users(.:format)                                 devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                            devise/registrations#edit
#                          PATCH  /users(.:format)                                 devise/registrations#update
#                          PUT    /users(.:format)                                 devise/registrations#update
#                          DELETE /users(.:format)                                 devise/registrations#destroy
#                     root GET    /                                                dashboard#index
#     unauthenticated_root GET    /                                                home#index
#     profile_appointments POST   /profiles/:profile_id/appointments(.:format)     appointments#create
#  new_profile_appointment GET    /profiles/:profile_id/appointments/new(.:format) appointments#new
#      profile_appointment PATCH  /profiles/:profile_id/appointments/:id(.:format) appointments#update
#                          PUT    /profiles/:profile_id/appointments/:id(.:format) appointments#update
#             edit_profile GET    /profiles/:id/edit(.:format)                     profiles#edit
#                  profile GET    /profiles/:id(.:format)                          profiles#show
#                          PATCH  /profiles/:id(.:format)                          profiles#update
#                          PUT    /profiles/:id(.:format)                          profiles#update
#

Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'settings' => 'dashboard#settings'
  get 'book-class' => 'dashboard#book_class'
  post 'book-class' => 'dashboard#book_class_search'
  get 'class-history' => 'dashboard#class_history'

  devise_for :users

  authenticated :user do
    root 'dashboard#index', as: :root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

  resources :profiles, only: [:show, :update, :edit] do
    resources :educations , only: [ :update, :edit, :create]
    resources :experiences , only: [ :update, :edit, :create]
    # creating the appointments for the user.
    resources :appointments, only: [:new, :update, :create] do
      resources :payments, only: [:new, :create] do
        member do
          get 'make'
          post 'confirm'
        end
      end
      member do
        put 'accept_class'
        put 'cancel_class'
        put 'start_class'
      end
    end

    resources :cards, only: [:new, :create, :destroy]

    get 'payments/pending' => 'payments#pending', as: :pending_payments
    post 'payments#withdraw' => 'payments#withdraw', as: :withdraw_payments
  end

  resources :appointments, only: [] do
    resources :testimonials, only: [:create]
  end

  get 'messages' => 'messages#index', as: :messages
  get 'messages/:id/new' => 'messages#new', as: :new_message
  post 'messages/:id' => 'messages#create', as: :create_message
  post 'messages/:id/reply' => 'messages#reply', as: :reply_message
  get 'messages/:id/conversation' => 'messages#get_messages_list'

  get 'aboutus' => 'home#aboutus'
  get 'faq' => 'home#faq'
  get 'course' => 'home#course'
  get 'whywikilesson' => 'home#whywikilesson'
  get 'blog' => 'home#blog'
  get 'contactus' => 'home#contactus'
  get 'howitwork' => 'home#howitwork'

  # get the user class info.
  get 'classinfo/:id' => 'appointments#class_info'

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @conversations = current_user.mailbox.conversations
  end

  def new
    @user = User.find params[:id]
    redirect_to :back and return if current_user.id == @user.id
    redirect_to root_path and return unless @user.has_role? :teacher
    redirect_to messages_path if current_user.mailbox.conversations_with(@user).count > 0
  end

  def create
    @user = User.find params[:id]
    if params[:message][:message].length > 0
      redirect_to root_path unless @user.has_role? :teacher
      redirect_to messages_path if current_user.mailbox.conversations_with(@user).count > 0
      current_user.send_message(@user, params[:message][:message], 'Subject')
      redirect_to messages_path
    else
      render 'new'
    end
  end

  def reply
    if params[:message][:message].length > 0
      @conversation = current_user.mailbox.conversations.where(id: params[:id]).last
      current_user.reply_to_conversation(@conversation, params[:message][:message])
    end
    redirect_to messages_path
  end

  def get_messages_list
    @conversation = current_user.mailbox.conversations.where(id: params[:id]).last
  end

end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_messages_list.html.erb
<div class="sender-details-div chating-border-bottom date-day-wrapper">
  <div>
    <h3 class="sender-name"><%= get_other_participant(@conversation.participants).name %></h3>
    <p><%= current_role get_other_participant(@conversation.participants) %></p>
  </div>
  <div><p class="date-day">thursday, <span class="font-blue">february4,2016</span></p></div>
</div>
<div class="inner-scroll-div">
  <div class="old-messages-div">
    <% @conversation.receipts_for(current_user).each do |receipt| %>
        <div class="inner-border-bottom">
          <div class="image-message-div">
            <div>
              <div class="active-circle-div">
                <img src="<%= get_avatar(receipt.message.sender.profile) %>" alt="" width="70">
                <span class="active-circle"></span>
              </div>

            </div>
            <div class="messsage-full-details">
              <div class="sender-details-div">
                <h3 class="sender-name"><%= receipt.message.sender.name %>:</h3>
                <p><%= receipt.message.created_at %></p>
              </div>
              <p>
                <%= receipt.message.body %>
              </p>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>
<div class="text-box-div">
  <%= form_for 'message', url: reply_message_path(@conversation) do |f| %>
      <%= f.text_area :message, rows: 7 %>
      <div><button class="chating-send-button">Send</button></div>
  <% end %>
</div>

app/views/messages/get_messages_list.js.erb
$('#messages-wrapper').html('<%= j render 'messages_list' %>');

app/views/messages/index.html.erb
<section class="techer-profile-section chatting-hero-section">
  <div class="white-bg-chating clearfix">
    <div class="row">
      <div class="col-md-4">
        <div class="chating-border-bottom search-div-wrapper">
          <div class="search-div">
            <i class="fa fa-search fa-2x"></i>
            <input type="text" class="fontAwesome" placeholder="Search contacts" value="">
          </div>
        </div>
        <div id="scroll-left">
          <% @conversations.each do |conversation| %>
              <div class="left-side-mesages-wrapper load-messages" data-conversation="<%= conversation.id %>">
                <div class="inner-border-bottom left-side-messages-div">
                  <div class="center-flex"><i class="fa fa-comments-o fa-3x" aria-hidden="true"></i></div>
                  <div class="left-side-messages">
                    <div class="sender-details-div">
                      <h3 class="sender-name"><%= get_other_participant(conversation.participants).name %>:</h3>
                      <p><%= conversation.updated_at.strftime('%d %b, %y %l:%M%p') %></p>
                    </div>
                    <p><%= conversation.last_message.body %></p>
                  </div>
                </div>
              </div>
          <% end %>
        </div>
      </div>
      <div class="col-md-8 messages-wrapper" id="messages-wrapper">
        <% if @conversations.count > 0 %>
            <% @conversation = @conversations[0] %>
            <%= render 'messages_list' %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/messages/new.html.erb
<div class="container">
  <%= form_for 'message', url: create_message_path(@user) do |f| %>
      <legend style="margin-top: 20px;">Use this form to start your conversation:</legend>

      <div class="form-group">
        <%= f.label :message %>
        <%= f.text_area :message, class: 'form-control', rows: '10', placeholder: 'Write your message here...' %>
      </div>

      <div class="form-group">
        <%= f.submit value: 'Send message', class: 'btn btn-success' %>
      </div>
  <% end %>
</div>