config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#                dashboard GET    /dashboard(.:format)                             dashboard#index
#         new_user_session GET    /users/sign_in(.:format)                         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                        devise/sessions#destroy
#            user_password POST   /users/password(.:format)                        devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                   devise/passwords#edit
#                          PATCH  /users/password(.:format)                        devise/passwords#update
#                          PUT    /users/password(.:format)                        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                          devise/registrations#cancel
#        user_registration POST   /users(.:format)                                 devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                            devise/registrations#edit
#                          PATCH  /users(.:format)                                 devise/registrations#update
#                          PUT    /users(.:format)                                 devise/registrations#update
#                          DELETE /users(.:format)                                 devise/registrations#destroy
#                     root GET    /                                                dashboard#index
#     unauthenticated_root GET    /                                                home#index
#     profile_appointments POST   /profiles/:profile_id/appointments(.:format)     appointments#create
#  new_profile_appointment GET    /profiles/:profile_id/appointments/new(.:format) appointments#new
#      profile_appointment PATCH  /profiles/:profile_id/appointments/:id(.:format) appointments#update
#                          PUT    /profiles/:profile_id/appointments/:id(.:format) appointments#update
#             edit_profile GET    /profiles/:id/edit(.:format)                     profiles#edit
#                  profile GET    /profiles/:id(.:format)                          profiles#show
#                          PATCH  /profiles/:id(.:format)                          profiles#update
#                          PUT    /profiles/:id(.:format)                          profiles#update
#

Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'settings' => 'dashboard#settings'
  get 'book-class' => 'dashboard#book_class'
  post 'book-class' => 'dashboard#book_class_search'
  get 'class-history' => 'dashboard#class_history'

  devise_for :users

  authenticated :user do
    root 'dashboard#index', as: :root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

  resources :profiles, only: [:show, :update, :edit] do
    resources :educations , only: [ :update, :edit, :create]
    resources :experiences , only: [ :update, :edit, :create]
    # creating the appointments for the user.
    resources :appointments, only: [:new, :update, :create] do
      resources :payments, only: [:new, :create] do
        member do
          get 'make'
          post 'confirm'
        end
      end
      member do
        put 'accept_class'
        put 'cancel_class'
        put 'start_class'
      end
    end

    resources :cards, only: [:new, :create, :destroy]

    get 'payments/pending' => 'payments#pending', as: :pending_payments
    post 'payments#withdraw' => 'payments#withdraw', as: :withdraw_payments
  end

  resources :appointments, only: [] do
    resources :testimonials, only: [:create]
  end

  get 'messages' => 'messages#index', as: :messages
  get 'messages/:id/new' => 'messages#new', as: :new_message
  post 'messages/:id' => 'messages#create', as: :create_message
  post 'messages/:id/reply' => 'messages#reply', as: :reply_message
  get 'messages/:id/conversation' => 'messages#get_messages_list'

  get 'aboutus' => 'home#aboutus'
  get 'faq' => 'home#faq'
  get 'course' => 'home#course'
  get 'whywikilesson' => 'home#whywikilesson'
  get 'blog' => 'home#blog'
  get 'contactus' => 'home#contactus'
  get 'howitwork' => 'home#howitwork'

  # get the user class info.
  get 'classinfo/:id' => 'appointments#class_info'

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                   :integer          not null, primary key
#  firstname            :string(255)
#  lastname             :string(255)
#  avatar               :string(255)
#  phone1               :string(255)
#  phone2               :string(255)
#  about                :text(65535)
#  custom_video         :string(255)
#  user_id              :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  profile_status       :integer
#  verified             :boolean          default(FALSE)
#  rate                 :decimal(16, 2)
#  address              :string(255)
#  native_language      :string(255)
#  additional_languages :string(255)
#  standard             :integer
#  stripe_customer_id   :string(255)
#  average_rating       :float(24)        default(0.0)
#  gender               :integer          default(0)
#  availability         :integer          default(1)
#  zone                 :string(255)
#
# Indexes
#
#  index_profiles_on_stripe_customer_id  (stripe_customer_id)
#  index_profiles_on_user_id             (user_id)
#
# Foreign Keys
#
#  fk_rails_e424190865  (user_id => users.id)
#

class Profile < ActiveRecord::Base
  acts_as_taggable_on :subjects
  mount_uploader :avatar, AvatarUploader
  belongs_to :user
  has_many :educations
  has_many :experiences

  # validates_presence_of :firstname, :phone1

  # This is for the skill section that would be used to determine what the teacOher will be teaching.


  #   Creating the profile completeness
  PROFILE_COMPLETENESS_TEACHER = %w(firstname avatar phone1 about rate address native_language additional_languages standard educations experiences)
  PROFILE_COMPLETENESS_STUDENT = %w(firstname avatar phone1 about address native_language additional_languages standard)

  STANDARD = {
      0 => 'Standard 1',
      1 => 'Standard 2',
      2 => 'Standard 3',
      3 => 'Standard 4'
  }

  GENDER = {
      0 => 'Male',
      1 => 'Female'
  }

  GENDER_GET = {
      'male' => 0,
      'female' => 1
  }

  AVAILABILITY = {
      0 => 'Offline',
      1 => 'Online'
  }

  AVAILABILITY_GET = {
      'online' => 1,
      'offline' => 0
  }

  before_update :update_profile_progress
  after_create :create_stripe_customer

  def fullname
    "#{self.firstname} #{self.lastname}"
  end

  def video
    link = self.custom_video.split('=').last if self.custom_video
    if link.empty?
      link = self.custom_video.split('/').last if self.custom_video
    end
    link
  end

  private

  def update_profile_progress
    progress = 0
    if self.user.has_role? :teacher
      PROFILE_COMPLETENESS_TEACHER.each do |field|
        unless self.send(field).blank?
          progress = progress + 1
        end
      end
      self.profile_status = ( progress.to_f / PROFILE_COMPLETENESS_TEACHER.length * 100).to_i
    else
      PROFILE_COMPLETENESS_STUDENT.each do |field|
        unless self[field].blank?
          progress = progress + 1
        end
      end
      self.profile_status = ( progress.to_f / PROFILE_COMPLETENESS_STUDENT.length * 100).to_i
    end
  end

  def create_stripe_customer
    customer = Stripe::Customer.create(email: self.user.email)
    self.update(stripe_customer_id: customer.id)
  end
end

app/controllers/profiles_controller.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :integer          not null, primary key
#  firstname    :string(255)
#  lastname     :string(255)
#  avatar       :string(255)
#  phone1       :string(255)
#  phone2       :string(255)
#  about        :text(65535)
#  custom_video :string(255)
#  user_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ProfilesController < ApplicationController

  before_action :set_profile, only: [:show, :update, :edit]
  before_action :authenticate_user!, except: [:show]

  def show
    if current_user == @profile.user
      if @profile.profile_status < 81
        redirect_to edit_profile_path(@profile), notice: 'Your profile needs to be 100% complete.'
      end
    elsif @profile.profile_status != 100
      redirect_to root_path, notice: 'They haven\'t completed their profile.'
    end

    @education = @profile.educations.new

    @all_education = @profile.educations.all
    @experience = @profile.experiences.all
    @two_subject = @profile.experiences.first(2)
    @new_experience = @profile.experiences.new
    @tags = @profile.subjects
    @total_hours = Appointment.where(teacher_id: @profile.user_id, class_status: 3).sum(:class_hours)
    @total_classes = Appointment.where(teacher_id: @profile.user_id, class_status: 3).count(:id)

    @is_teacher = @profile.user.has_role? :teacher
  end


  def edit
    redirect_to root_path unless current_user.id == @profile.user_id
  end


  def update
    if @profile.update(profile_params)
      respond_to do |format|
        format.html {
          flash[:notice] = 'Profile Updated Successfully'
          redirect_to @profile
        }

        # format.json { render :show, status: :ok, location: @profile }

        format.js { render json: @profile }
      end
    else
      respond_to do |format|
        format.html{
          render :edit
        }

        format.json { render json: @profile.errors, status: :unprocessable_entity }
        format.js { render json: @profile.errors, status: :unprocessable_entity }

      end

    end
  end

  private

  def set_profile
    @profile = Profile.find(params[:id])
  end

  def profile_params
    params.require(:profile).permit(:firstname, :lastname, :about, :avatar, :custom_video, :phone1, :phone2, :tag_list, :address, :native_language, :additional_languages, :standard, :rate, :subject_list, :availability, :zone)
  end

end

app/views/profiles/_customvideo.html.erb
<section class="invite-friend-section border-top-blue padding-v-10">
  <section class="login-details-div">
<%= simple_form_for(@profile, :html => { :class => 'form-horizontal login-form-container login-form-div' }) do |f| %>

    <div class="form-group login-flex">
      <div class="col-sm-12 col-md-12 col-xs-12 input-flex after-select">
        <label for="" class="login-label">Your Video Link</label>

        <div class="input-div">
          <%= f.input :custom_video,placeholder: "put link here", label: false, class: "login-icon-white" %>
        </div>
      </div>
    </div>


    <div class="form-group">
      <label for="" class="col-sm-12 col-xs-12 col-md-12 login-btn-div">

        <%= f.submit "UPDATE", :class => "login-btn" %>
      </label>
    </div>

<% end %>
    </section>
</section>

app/views/profiles/_education.html.erb
<section class="invite-friend-section border-top-blue padding-v-10">
  <section class="login-details-div">

    <%= simple_form_for([@profile,@education], :html => { :class => 'form-horizontal login-form-container login-form-div' }) do |f| %>



        <div class="form-group login-flex">


          <div class="col-sm-12 col-md-12 input-flex">
            <label for="" class="login-label">school</label>
            <div class="input-div"><%= f.input :school, label: false %></div>
          </div>
        </div>


        <div class="form-group login-flex">
          <div class="col-sm-6 col-md-6 input-flex">
            <label for="" class="login-label">year from</label>
            <div class="input-div"><%= f.input :year_from,:as => :date,
                                               :start_year => 1970, :end_year => Date.current.year, :order => [ :year], label: false %></div>
          </div>
          <div class="col-sm-6 col-md-6 input-flex">
            <label for="" class="login-label">year to</label>
            <div class="input-div"><%= f.input :year_to,:as => :date,
                                               :start_year => 1970, :end_year => Date.current.year, :order => [ :year], label: false %></div>
          </div>
        </div>

        <div class="form-group login-flex">
          <div class="col-sm-12 col-md-12 col-xs-12 input-flex after-select">
            <label for="" class="login-label">Description</label>

            <div class="input-div">
              <%= f.input :description, label: false %>
            </div>
          </div>
        </div>



        <div class="form-group">
          <label for="" class="col-sm-12 col-xs-12 col-md-12 login-btn-div">

            <%= f.submit "submit", :class => "login-btn" %>
          </label>
        </div>

    <% end %>
  </section>
</section>

app/views/profiles/_experience.html.erb
<section class="invite-friend-section border-top-blue padding-v-10">
  <section class="login-details-div">

    <%= simple_form_for([@profile,@new_experience], :html => { :class => 'form-horizontal login-form-container login-form-div' }) do |f| %>



        <div class="form-group login-flex">


          <div class="col-sm-12 col-md-12 input-flex">
            <label for="" class="login-label">subject</label>
            <div class="input-div"><%= f.input :subject, label: false %></div>
          </div>
        </div>

        <div class="form-group login-flex">
          <div class="col-sm-12 col-md-12 col-xs-12 input-flex after-select">
            <label for="" class="login-label">Description</label>
            <div class="input-div">
              <%= f.input :description, label: false %>
            </div>
          </div>
        </div>

        <div class="form-group login-flex">
          <div class="col-sm-12 col-md-12 input-flex">
            <label for="" class="login-label">experience</label>
            <div class="input-div"><%= f.input :experience_time, label: false %></div>
          </div>
        </div>



        <div class="form-group">
          <label for="" class="col-sm-12 col-xs-12 col-md-12 login-btn-div">

            <%= f.submit "submit", :class => "login-btn" %>
          </label>
        </div>

    <% end %>
        </section>
        </section>

app/views/profiles/_tagfield.html.erb
<section class="invite-friend-section border-top-blue padding-v-10">
  <section class="login-details-div">
    <%= simple_form_for(@profile, :html => { :class => 'form-horizontal login-form-container login-form-div' }) do |f| %>

        <div class="form-group login-flex">
          <div class="col-sm-12 col-md-12 col-xs-12 input-flex after-select">
            <label for="" class="login-label">Write your subject separated by comma</label>

            <div class="input-div">

              <%= f.input :subject_list, input_html: { data:{role: 'tagsinput'}, value: @profile.subject_list.join(',')}, label: false, class: "login-icon-white" %>

            </div>
          </div>
        </div>


        <div class="form-group">
          <label for="" class="col-sm-12 col-xs-12 col-md-12 login-btn-div">

            <%= f.submit "UPDATE", :class => "login-btn" %>
          </label>
        </div>

    <% end %>
  </section>
</section>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<div class="view">
  <section class="techer-profile-section">
    <div class="review-div">
      <h3>
        <% if @is_teacher %>
            Teacher Profile
        <% else %>
            Student Profile
        <% end %>

      </h3>
      <div>
        <span class="review-text">Average rating:</span>
        <% if @profile.user.testimonials.average(:rating) %>
            <% (1..@profile.user.testimonials.average(:rating).ceil.to_i).each do |a| %>
                <i class="fa fa-star icon-star"></i>
            <% end %>
        <% end %>
        <span class="review-text">(<%= @profile.user.testimonials.count %> reviews)</span>
      </div>
    </div>
    <div class="bg-white">
      <div class="row circl-imgdiv">
        <div class="col-md-5 col-xs-6 col-sm-3 circle-row">

          <% if @profile.avatar.present? %>
              <%= image_tag @profile.avatar_url(:thumb), class: 'aditya-pic' %>
          <% end %>
        </div>
        <div class="col-md-7 col-xs-6 col-sm-9 circle-row">
          <div class="aditya-col">
            <h4 class="aditya-h4"><span class="h4-bold"><%= @profile.fullname %></span> <% if @profile.user == current_user %><%= link_to edit_profile_path do %> <span><i class = "fa fa-pencil"></i></span><% end %> <% end %></h4>




            <h4 class="doller-h4" data-toggle="modal" data-target="#rateModal">

              <% if @is_teacher %>
                  <% if @profile.rate.present? %>
                      <%= number_to_currency(@profile.rate) %>/hr
                  <% else %>
                      $0.00/hr <div style="color: #cc3333; font-size: 10px;">( Please change this. )</div>
                  <% end %>

              <% end %>

            </h4>

            <div class="modal fade bs-example-modal-lg" id="rateModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Change hourly Rate</h4>
                  </div>
                  <div class="modal-body">
                    <p>Please change your hourly rate here. WikiLessons will deduct a percentage of 12% from the amount that you enter.</p>
                    <table>
                      <tr>
                        <td>
                          <b>Hourly Rate</b>
                          <p>This is the amount the client will see</p>
                        </td>
                        <td class="value-side">
                          <label for="">$</label>
                          <input id="value_a" type="text">
                          <span>/ hr</span>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>12% Wiki Lesson service fee</b>
                        </td>
                        <td class="value-side">
                          <label for="">$</label>
                          <input id="serviceval" class="transinput" type="text">
                          <span>/ hr</span>
                        </td>
                      </tr>
                      <tr>
                        <td>
                          <b>You'll recieve</b>
                          <p>The estimated amount you'll recieve after service fee.</p>
                        </td>
                        <td class="value-side">
                          <label for="">$</label>
                          <input id="final" type="text">
                          <span>/ hr</span>
                        </td>
                      </tr>

                    </table>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-success" id="save_newrate_button" data-profileid="<%= @profile.id %>">Save</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div>
            <% if @profile.user.has_role? :teacher %>
                <%= link_to 'Send Message', new_message_path(id: @profile.user_id) %>
            <% end %>
            <div class="div-with-more-subject">
              <% if @tags.any? %>

                  <% @tags.each do |f| %>
                      <button class="btn-grey" type="button" name="button"><%= f.name %></button>
                  <% end %>

              <% else %>
                  <p>No subjects added. Please add your speciality.</p>


              <% end %>
            </div>
          </div>


          <% if @profile.user != current_user %>

              <div>
                <div id="book-app">

                  <book-class teacherid="<%= @profile.id %>"></book-class>

                </div>
              </div>
          <% end %>
        </div>
      </div>

      <div class="row profile-progress-div">
        <div class="col-md-6">
          <p><span class="font-blue"><%= @profile.profile_status %>%</span> Basic Profile Completion</p>
          <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:<%= @profile.profile_status %>%">
            </div>
          </div>
        </div>
        <div class="col-md-6 right-worked-history">
          <h4>Class history:</h4>
          <p><span><%= pluralize @total_hours, 'hour', 'hours' %></span> taught.</p>
          <p><%= pluralize @total_classes, 'class', 'classes' %></p>
        </div>
      </div>

      <div  class="techer-profile-section bg-white">
        <div class="personal-description-div">

          <% if @profile.user == current_user %>
              <span id="add_education" class="add_skill"><span class="font-circle"><i class="fa fa-plus"></i></span>Edit Subjects</span>
              <div class="section-of-form-for-experience" id ="skill_form"><%= render 'profiles/tagfield' %></div>
          <% end %>
        </div>
      </div>

      <div class="video-border">

        <% if @profile.custom_video.present? %>
            <div class="embed-responsive embed-responsive-16by9">
              <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/<%= @profile.video %>"></iframe>
            </div>
        <% end %>
        <% if @profile.user == current_user %>
            <div class="video-upload-div">

            <span class="video-circle">
              <i class="fa fa-play" aria-hidden="true"></i>
            </span>
              <h3>place video</h3>
            </div>
            <div id="video-url" class="section-of-form-for-experience"><%= render 'profiles/customvideo' %></div>
        <% end %>


      </div>

      <div class="overview-div personal-description-div">
        <h3 class="description-h3 heading-border-bottom">description:<% if @profile.user == current_user %><%= link_to edit_profile_path do %> <span><i class = "fa fa-pencil"></i></span> <% end %> <% end %> </h3>
        <p>
          <%= @profile.about %>
        </p>
      </div>
    </div>

    <div  class="techer-profile-section bg-white">
      <div class="personal-description-div">
        <h3 class="description-h3 heading-border-bottom">teaching <span class="word_color">experience:</span></h3>
        <ul class="personal-description-border">
          <% @experience.each do |f| %>
              <li>
                <p><span class="word_color"><%= f.subject %>-</span>  <%= f.description %></p>
              </li>
          <% end %>
        </ul>
        <% if current_user == @profile.user  %>

            <span id="add_education" class="add_experience"><span class="font-circle"><i class="fa fa-plus"></i></span>Add Experience</span>
            <div class="row section-of-form-for-experience" id="experience_form">
              <%= render 'profiles/experience' %>
            </div>

        <% end %>
      </div>
    </div>
    <div  class="techer-profile-section bg-white">
      <div class="personal-description-div">
        <h3 class="description-h3 heading-border-bottom">teaching <span class="word_color">approach:</span></h3>
        <div class="personal-description-border">
          <p>A variety which are flexible and dependent on the student</p>
        </div>

      </div>
    </div>
    <div  class="techer-profile-section bg-white">
      <div class="personal-description-div">
        <h3 class="description-h3 heading-border-bottom">qualifications:</h3>

        <ul class="personal-description-border">
          <% @all_education.each do |f| %>
              <li>
                <p><span class="word_color"><%= f.school %>(<%= f.year_from.strftime("%Y") %> - <%= f.year_to.strftime("%Y") %>)-</span>  <%= f.description %></p>
              </li>

          <% end %>

        </ul>
        <% if current_user == @profile.user  %>

            <span id="add_education" class="add_education"><span class="font-circle"><i class="fa fa-plus"></i></span>Add Education</span>
            <div class="row section-of-form-for-experience" id="education_form">
              <%= render 'profiles/education' %>
            </div>
        <% end %>
      </div>
    </div>
    <div  class="techer-profile-section bg-white">
      <div class="maps-div">
        <div class="row">
          <div class="col-md-6 col-sm-12 col-xs-12 ">
            <div class="extra-map-para hidden-sm hidden-lg hidden-md" >
              <p>native language: english (british)</p>
              <p>additional language: chinese, portuguise, malay</p>
              <p>profile links: <a href="">http://www.wikilesson.com</a> </p>
            </div>
            <div class="mapspara">

              <div class="mapspara-heading">
                <p>native language:</p>
                <p>additional language:</p>
                <p>profile links: </p>

              </div>
              <div class="maps-para-right">
                <p><%= @profile.native_language %></p>
                <p><%= @profile.additional_languages %></p>
                <a href="">http://www.wikilesson.com</a>
                <p class="copy-link">copy link</p>
                <div style="height: 95px;"></div>
              </div>
            </div>

          </div>
          <div class="col-md-6 col-sm-12 col-xs-12 ">
            <h3 class="description-h3">location:</h3>
            <div id="map">
            </div>


          </div>

        </div>
        <h3 class="description-h3">share it <span class="word_color">with:</span></h3>
        <div class="social-link-btns">
          <button class="btn-blue" type="button" name="button"><i class="fa fa-facebook"></i>facebook</button>
          <button class="btn_twitter" type="button" name="button"><i class="fa fa-twitter"></i>twitter</button>
          <button class="btn-navyblue"type="button" name="button"><i class="fa fa-linkedin"></i>linkedin</button>
        </div>
      </div>
    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCUx6QUI6AoZvDswOgJZA30e3_0l1UJGg8"></script>
  </section>
</div>