config/routes.rb
# == Route Map
#
#                   Prefix Verb   URI Pattern                                      Controller#Action
#                dashboard GET    /dashboard(.:format)                             dashboard#index
#         new_user_session GET    /users/sign_in(.:format)                         devise/sessions#new
#             user_session POST   /users/sign_in(.:format)                         devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)                        devise/sessions#destroy
#            user_password POST   /users/password(.:format)                        devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)                    devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format)                   devise/passwords#edit
#                          PATCH  /users/password(.:format)                        devise/passwords#update
#                          PUT    /users/password(.:format)                        devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)                          devise/registrations#cancel
#        user_registration POST   /users(.:format)                                 devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)                         devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)                            devise/registrations#edit
#                          PATCH  /users(.:format)                                 devise/registrations#update
#                          PUT    /users(.:format)                                 devise/registrations#update
#                          DELETE /users(.:format)                                 devise/registrations#destroy
#                     root GET    /                                                dashboard#index
#     unauthenticated_root GET    /                                                home#index
#     profile_appointments POST   /profiles/:profile_id/appointments(.:format)     appointments#create
#  new_profile_appointment GET    /profiles/:profile_id/appointments/new(.:format) appointments#new
#      profile_appointment PATCH  /profiles/:profile_id/appointments/:id(.:format) appointments#update
#                          PUT    /profiles/:profile_id/appointments/:id(.:format) appointments#update
#             edit_profile GET    /profiles/:id/edit(.:format)                     profiles#edit
#                  profile GET    /profiles/:id(.:format)                          profiles#show
#                          PATCH  /profiles/:id(.:format)                          profiles#update
#                          PUT    /profiles/:id(.:format)                          profiles#update
#

Rails.application.routes.draw do

  get 'dashboard' => 'dashboard#index'
  get 'settings' => 'dashboard#settings'
  get 'book-class' => 'dashboard#book_class'
  post 'book-class' => 'dashboard#book_class_search'
  get 'class-history' => 'dashboard#class_history'

  devise_for :users

  authenticated :user do
    root 'dashboard#index', as: :root
  end

  unauthenticated :user do
    root 'home#index', as: :unauthenticated_root
  end

  resources :profiles, only: [:show, :update, :edit] do
    resources :educations , only: [ :update, :edit, :create]
    resources :experiences , only: [ :update, :edit, :create]
    # creating the appointments for the user.
    resources :appointments, only: [:new, :update, :create] do
      resources :payments, only: [:new, :create] do
        member do
          get 'make'
          post 'confirm'
        end
      end
      member do
        put 'accept_class'
        put 'cancel_class'
        put 'start_class'
      end
    end

    resources :cards, only: [:new, :create, :destroy]

    get 'payments/pending' => 'payments#pending', as: :pending_payments
    post 'payments#withdraw' => 'payments#withdraw', as: :withdraw_payments
  end

  resources :appointments, only: [] do
    resources :testimonials, only: [:create]
  end

  get 'messages' => 'messages#index', as: :messages
  get 'messages/:id/new' => 'messages#new', as: :new_message
  post 'messages/:id' => 'messages#create', as: :create_message
  post 'messages/:id/reply' => 'messages#reply', as: :reply_message
  get 'messages/:id/conversation' => 'messages#get_messages_list'

  get 'aboutus' => 'home#aboutus'
  get 'faq' => 'home#faq'
  get 'course' => 'home#course'
  get 'whywikilesson' => 'home#whywikilesson'
  get 'blog' => 'home#blog'
  get 'contactus' => 'home#contactus'
  get 'howitwork' => 'home#howitwork'

  # get the user class info.
  get 'classinfo/:id' => 'appointments#class_info'

end

app/views/layouts/_alerts.html.erb
<% if alert %>
    <div class="alert alert-danger alert-dark hidden-print">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= alert %>
    </div>
<% end %>

<% if notice %>
    <div class="alert alert-info alert-dark hidden-print">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= raw notice %>
    </div>
<% end %>

app/views/layouts/_externalnavbar.html.erb
<%= render 'layouts/navbar_dark_top' %>

<nav class="navbar navbar-default bottom-navbar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" style="margin-top:0" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand' do %>
        <%= image_tag 'logo.png', width:'80' %>

      <%end%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav navbar-right">

       <% if user_signed_in? %>

            <li><%= link_to 'Dashboard', root_path %><span class="a-border hidden-sm hidden-xs"></span></li>
            <li><%= link_to 'My Profile', profile_path(current_user.profile) %><span class="a-border hidden-sm hidden-xs"></span></li>
            <li><%= link_to 'Class History', class_history_path %><span class="a-border hidden-sm hidden-xs"></span></li>
            <li><a href="<%= messages_path %>">Messages</a><span class="a-border hidden-sm hidden-xs"></span></li>

            <% unless current_user.has_role? :teacher %>
            <li><a href="<%= book_class_path %>">Book Class</a><span class="a-border hidden-sm hidden-xs"></span></li>
            <% end %>

            <li><a href="#">Payments</a><span class="a-border hidden-sm hidden-xs"></span></li>
            <li><a href="<%= settings_path %>">Settings</a><span class="a-border hidden-sm hidden-xs"></span></li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-bell nav-user-icon" aria-hidden="true"></i><span style="color: #cc3333"> ( 12 ) </span><span class="caret"></span></a>
              <ul class="dropdown-menu" id="notifications-list">
                <li><%= image_tag asset_path('loader.gif'), class: 'img-responsive', id: 'loader-gif', width: 50 %></li>
              </ul>
            </li>

        <% else %>

            <%= render 'layouts/logged_out_links.html.erb' %>

        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_footer.html.erb
<section class="footer-hidden-div hidden-lg hidden-md hidden-sm ">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-sm-6 col-xs-6">
        <h4 class="footer-h4">quick links</h4>
        <ul>
          <li><a href="" class="footer-a">home</a></li>
          <li><a href="" class="footer-a">courses</a></li>
          <li><a href="" class="footer-a">sign up</a></li>
          <li><a href="" class="footer-a">about us</a></li>
          <li><a href="" class="footer-a">careers</a></li>
          <li><a href="" class="footer-a">about us</a></li>
        </ul>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-6 footer-mid-col">
        <h4 class="footer-h4">info</h4>
        <ul>
          <li><a href="" class="footer-a">become a teacher</a></li>
          <li><a href="" class="footer-a">benifits</a></li>
          <li><a href="" class="footer-a">why wiki lesson</a></li>
          <li><a href="" class="footer-a">news</a></li>
          </ul>
      </div>
      <div class="col-md-12 col-sm-12 col-xs-12 footer-rightcol">
        <a href=""></i><i class="fa fa-twitter border-twitter"></i></a>
        <a href=""><i class="fa fa-tumblr border-tumbler border-fb" aria-hidden="true"></i></a>
        <a href=""><i class="fa fa-facebook border-tumbler"></i></a>
        <p>+91 0145779787</p>
        <a href="" class="email-a">Question?learnwithus@wikilesson.com</a>
      </div>
    </div>
  </div>

</section>

<section class="footer-div">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-3 col-xs-3">
        <h4 class="footer-h4">quick links</h4>
        <ul>
          <li><a href="">home</a></li>
          <li><a href="">courses</a></li>
          <li><a href="">sign up</a></li>
          <li><a href="">about us</a></li>
          <li><a href="">careers</a></li>
          <li><a href="">about us</a></li>
        </ul>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-3 footer-mid-col">
        <h4 class="footer-h4">info</h4>
        <ul>
          <li><a href="">become a teacher</a></li>
          <li><a href="">benifits</a></li>
          <li><a href="">why wiki lesson</a></li>
          <li><a href="">news</a></li>
          </ul>
      </div>
      <div class="col-md-6 col-sm-6 col-xs-6 footer-rightcol">
        <div class="footer-icon-div">
          <div class="footer-icon"><a href=""></i><i class="fa fa-twitter "></i></a></div>
          <div class="footer-icon"><a href=""><i class="fa fa-tumblr " aria-hidden="true"></i></a></div>
          <div class="footer-icon"><a href=""></i><i class="fa fa-facebook "></i></a></div>

        </div>
        <p>+91 0145779787</p>
        <a href="" class="email-a">Question?learnwithus@wikilesson.com</a>
      </div>
    </div>


  </div>

</section>

<footer class="footer-section">
  <div class="container lastdiv">
    <ul class="list-inline left-ul">
      <li><a href="">site maps</a></li>
      <li><a href="">legals</a></li>
      <li><a href="">accessibility</a></li>
      <li><a href="">contact us</a></li>

    </ul>
    <ul class="list-inline right-ul">
      <li><a href="" >copyright 2016-2017</a></li>

    </ul>


  </div>

</footer>

app/views/layouts/_logged_out_links.html.erb
<li>
  <%= link_to "home", root_path %><span class="a-border hidden-sm hidden-xs"></span>
</li>
<li class="dropdown" >
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">about us <span class="caret"></span></a>
  <ul class="dropdown-menu">
    <li>
      <%= link_to "about us", aboutus_path %>
    </li>
    <li> <%= link_to "how does it work", howitwork_path %></li>
  </ul>
  <span class="a-border hidden-sm hidden-xs"></span>
</li>
<li>
  <%= link_to "faq", faq_path %><span class="a-border hidden-sm hidden-xs"></span>
</li>
<li><%= link_to "course", course_path %><span class="a-border hidden-sm hidden-xs"></span></li>
<li><%= link_to "why wiki lesson", whywikilesson_path %><span class="a-border hidden-sm hidden-xs"></span></li>
<li><%= link_to "blog", blog_path %><span class="a-border hidden-sm hidden-xs"></span></li>
<li><%= link_to "contact us", contactus_path %><span class="a-border hidden-sm hidden-xs"></span></li>

app/views/layouts/_navbar_dark_top.html.erb
<nav class="navbar navbar-default navbar-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <div>
        <a class="navbar-brand" href="#">
          <a href=""></i><i class="fa fa-twitter "></i></a>
          <a href=""><i class="fa fa-tumblr border-tumbler navbar-twitter" aria-hidden="true"></i></a>
          <a href=""><i class="fa fa-facebook"></i></a>
        </a>
      </div>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <ul class="nav navbar-nav">
      <i class="fa fa-lock navbar-lock" aria-hidden="true"></i>

      <% if user_signed_in? %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button' %>
      <% else %>
          <%= link_to 'login', new_user_session_path, class: 'button' %>

         <%= link_to 'Register', new_user_registration_path, class: 'button' %>
    <% end %>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= get_seo_title %></title>
  <meta name="description" content="<%= get_seo_description %>">
  <meta name="keywords" content="<%= get_seo_keywords %>">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="mainapp">
  <%= render 'layouts/externalnavbar'%>
  <%= yield %>
  <%= render 'layouts/footer'%>
</div>


<% if user_signed_in? %>
    <!--Insert all the templates here-->
    <%= render 'vuecomponents/booking_component' %>

<% end %>

<%= insert_paloma_hook %>
<script type="text/javascript" src="https://js.stripe.com/v2/"></script>

<!--Analytics starts here.-->

<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-91142802-1', 'auto');
    ga('send', 'pageview');

</script>

<!--Analytics ends here.-->

<!--Start of Tawk.to Script-->
<script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/585a108b7295ad7394fcb397/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
    })();
</script>
<!--End of Tawk.to Script-->

<%= javascript_include_tag 'application' %>
<% if user_signed_in? %>
<script src="https://www.gstatic.com/firebasejs/3.6.3/firebase.js"></script>

    <!--Analytics starts here.-->

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-91142802-1', 'auto');
        ga('send', 'pageview');

    </script>

    <!--Analytics ends here.-->
<script>
    var config = {
        apiKey: "AIzaSyBd4h5IwaXJljPbb3rsDfp3U5W8-NHfxxk",
        authDomain: "wiki-lessons.firebaseapp.com",
        databaseURL: "https://wiki-lessons.firebaseio.com",
        storageBucket: "wiki-lessons.appspot.com",
        messagingSenderId: "1067952415099"
    };
    firebase.initializeApp(config);
    var v = firebase.database().ref('notifications-<%= current_user.id  %>');
    v.on('value', function (snapshot) {
        var list = (snapshot.val());
        $('#loader-gif').remove();
        $('#empty-notification').remove();
        if(list){
            var keys = (Object.keys(snapshot.val()));
            keys.forEach(function (a) {
                $('#notifications-list').prepend('<li><a href="' + list[a].link + '">' + list[a].message + '</a></li>')
            });
        }else{
            $('#notifications-list').append('<li id="empty-notification"><a href="#">You do not have any notifications.</a></li>')
        }
    });
</script>
<% end %>

</body>
</html>